######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 28 01:51:25 2009
######################################################################

SOURCES += ../src/macaddress.cpp 
HEADERS += ../src/macaddress.h
DEFINES += __TESTING__
TEMPLATE = subdirs
SUBDIRS = mac \ 
	ippacket \
	ipaddress \
	frame \
	boxchip \
	routemodel 
# Input
